version: '3' 
services: 
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
    volumes:
      - rabbit:/var/lib/rabbitmq
  app:  
    build: . 
    command: rails s -b 0.0.0.0  
    volumes: 
      - .:/usr/src 
    ports: 
      - "3000:3000" 
    depends_on:
      - rabbitmq
volumes:
  rabbit: